all:
  hosts:
    localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
    jenkins-master:
      ansible_host: 56.228.39.35
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /openssh-keys/EC2KeyPair.pem
    monitoring:
      ansible_host: 13.49.99.125
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /openssh-keys/EC2KeyPair.pem